name: "choro_live_ephemeral"

services:
  choro.horizon:
    image: ghcr.io/tefabi/choro_cli:${CHORO_VERSION}
    # We can override any env values here.
    # By default the .env in the project root will be loaded as the environment for all containers
    env_file:
      - .env.production
    restart: unless-stopped
    networks:
      - choro-network
    command: sh -c "php /opt/apps/www/artisan horizon"

  choro.reverb:
    image: ghcr.io/tefabi/choro_cli:${CHORO_VERSION}
    # We can override any env values here.
    # By default the .env in the project root will be loaded as the environment for all containers
    env_file:
      - .env.production
    restart: unless-stopped
    networks:
      - choro-network
    ports:
      - "3090:8080"
    command: sh -c "php /opt/apps/www/artisan reverb:start --debug -vvv"

  choro.schedule:
    image: ghcr.io/tefabi/choro_cli:${CHORO_VERSION}
    # We can override any env values here.
    # By default the .env in the project root will be loaded as the environment for all containers
    env_file:
      - .env.production
    restart: unless-stopped
    networks:
      - choro-network
    command: sh -c "php /opt/apps/www/artisan schedule:work"

  # We need to run the FPM container for our application
  choro.fpm:
    image: ghcr.io/tefabi/choro_fpm_server:${CHORO_VERSION}
    # We can override any env values here.
    # By default the .env in the project root will be loaded as the environment for all containers
    env_file:
      - .env.production
    restart: unless-stopped
    networks:
      - choro-network
    post_start:
      # - command: php /opt/apps/www/artisan migrate:fresh --force --seed
      - command: php /opt/apps/www/artisan migrate --force
        user: www-data
      - command: php /opt/apps/www/artisan optimize
        user: www-data

  # Run the web server container for static content, and proxying to our FPM container
  choro.web:
    image: ghcr.io/tefabi/choro_nginx_server:${CHORO_VERSION}
    # Expose our application port (80) through a port on our local machine (8080)
    ports:
      - "3080:80"
    environment:
      # We need to pass in the new FPM hst as the name of the fpm container on port 9000
      FPM_HOST: "choro.fpm:9000"
    depends_on:
      - "choro.fpm"
    restart: unless-stopped
    networks:
      - choro-network

networks:
  choro-network:
    external: true
